name: Validate Data Schema (HumidityArtSocial)

on:
  [push, pull_request]

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jsonlint
        run: npm install -g @prantlf/jsonlint

      - name: Validate HumidityArtSocialDB.json
        run: jsonlint $GITHUB_WORKSPACE/HumidityArtSocialDB.json
